// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.Api.Data;

#nullable disable

namespace TaskManager.Api.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.12")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("TaskManager.Api.Models.AppUser", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime2");

            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(254)
                .HasColumnType("nvarchar(254)");

            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("nvarchar(512)");

            b.HasKey("Id");

            b.HasIndex("Email")
                .IsUnique();

            b.ToTable("Users");
        });

        modelBuilder.Entity("TaskManager.Api.Models.TaskItem", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("datetime2")
                .HasDefaultValueSql("SYSUTCDATETIME()");

            b.Property<string>("Description")
                .HasMaxLength(2000)
                .HasColumnType("nvarchar(2000)");

            b.Property<DateTime?>("DueDate")
                .HasColumnType("datetime2");

            b.Property<bool>("IsCompleted")
                .ValueGeneratedOnAdd()
                .HasColumnType("bit")
                .HasDefaultValue(false);

            b.Property<int>("Priority")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .HasDefaultValue(2);

            b.Property<int>("Status")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .HasDefaultValue(0);

            b.Property<string>("Title")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("datetime2");

            b.Property<int>("UserId")
                .HasColumnType("int");

            b.HasKey("Id");

            b.HasIndex("CreatedAt");
            b.HasIndex("DueDate");
            b.HasIndex("Priority");
            b.HasIndex("Status");
            b.HasIndex("Status", "Priority", "DueDate");
            b.HasIndex("UserId", "CreatedAt");
            b.HasIndex("UserId", "Status", "Priority", "DueDate");

            b.ToTable("TaskItems");
        });

        modelBuilder.Entity("TaskManager.Api.Models.TaskItem", b =>
        {
            b.HasOne("TaskManager.Api.Models.AppUser", "User")
                .WithMany("Tasks")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("User");
        });

        modelBuilder.Entity("TaskManager.Api.Models.AppUser", b =>
        {
            b.Navigation("Tasks");
        });
#pragma warning restore 612, 618
    }
}
